-- xmake l indexer/build_repology.lua --repo=<path-to-xmake-repo> --out=<output-file>
--
-- Publishes the Repology-compatible flat package index generated by
-- xmake-repo's own scripts/build_index.lua into this site's public output.

import("core.base.option")

local OPTIONS = {
    {nil, "repo", "kv", nil, "Path to a local xmake-repo checkout (default: ./xmake-repo)."},
    {nil, "out",  "kv", nil, "Output file or directory (default: ./dist/repology_packages_index.json)."},
}

function main(...)
    local args = option.parse({...}, OPTIONS, "Build the Repology package index.")
    local repo = args.repo or path.absolute("xmake-repo")
    local out = args.out or path.absolute("dist/repology_packages_index.json")
    if not out:match("%.json$") then
        out = path.join(out, "repology_packages_index.json")
    end

    local script = path.join(repo, "scripts", "build_index.lua")
    local generated = path.join(repo, "dist", "repology_packages_index.json")
    assert(os.isdir(repo), "repo dir not found: " .. repo)
    assert(os.isfile(script), "Repology indexer not found: " .. script)

    os.tryrm(generated)
    os.execv(os.programfile(), {"l", "scripts/build_index.lua"}, {curdir = repo})

    assert(os.isfile(generated), "Repology indexer did not produce: " .. generated)
    os.mkdir(path.directory(out))
    os.cp(generated, out)
    cprint("${green}wrote${clear} %s", out)
end
